name: NASA Project CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: use Node.js version 18
        uses: action/setup-node@v3
        with:
          node-version: "18"
      - run: npm install
      - run: npm run bild --prefix client
